name: Release Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Get latest
        id: latest-version
        uses: pozetroninc/github-action-get-latest-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft

      - name: Compare versions
        uses: madhead/semver-utils@latest
        id: version
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # Version being built
          version: ${{  github.ref_name }}
          # Compare to latest
          compare-to: ${{ steps.latest-version.outputs.release }}
      
      - name: Use latest
        if: ${{ steps.version.outputs.comparison-result }} == ">"
        run: |
          echo ${{ steps.version.outputs.comparison-result }}
          echo ${{ steps.latest-version.outputs.release }}
