# If you change this name also do it in linting-skipper.yml and ci_metrics.yml
name: Check Release Notes

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "**.py"
      - "pyproject.toml"
      - "!.github/**/*.py"
      - "!rest_api/**/*.py"

jobs:
  reno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            # With the default value of 1, there are corner cases where tj-actions/changed-files
            # fails with a `no merge base` error
            fetch-depth: 0

      - name: Get release note files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: releasenotes/notes/*.yaml

      - name: Check release notes
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
            echo "::error::Missing release notes file!"
            exit 1

