name: Release Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9].[0-9]+.[0-9]+
  
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   steps:
     - run: echo "HELO"
