name: Release Docker images

on:
  push:
    branches:
      - 'v[0-9].*[0-9].x'
    tags:
      - 'v[0-9].[0-9]+.[0-9]+*'
  
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   steps:
     - run: echo "HELO"
